# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BACommonModule-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'RxSwift'
  	pod 'RxCocoa'
	pod 'SnapKit'

  # Pods for BACommonModule-Swift

  target 'BACommonModule-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BACommonModule-SwiftUITests' do
    # Pods for testing
  end

end
